steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/robotic-gist-453607-t2/poshaX",
        "--build-arg=NEXT_PUBLIC_STEADFAST_API_ID=$(NEXT_PUBLIC_STEADFAST_API_ID)",
        "--build-arg=NEXT_PUBLIC_STEADFAST_SECRET_KEY=$(NEXT_PUBLIC_STEADFAST_SECRET_KEY)",
        ".",
      ]
    secretEnv:
      - NEXT_PUBLIC_STEADFAST_API_ID
      - NEXT_PUBLIC_STEADFAST_SECRET_KEY

secrets:
  - secretEnv:
      NEXT_PUBLIC_STEADFAST_API_ID: projects/robotic-gist-453607-t2/secrets/NEXT_PUBLIC_STEADFAST_API_ID/versions/latest
      NEXT_PUBLIC_STEADFAST_SECRET_KEY: projects/robotic-gist-453607-t2/secrets/NEXT_PUBLIC_STEADFAST_SECRET_KEY/versions/latest
