steps:
  # 1. Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/robotic-gist-453607-t2/cloud-run-source-deploy/fc-frontend/fc-frontend",
        ".",
      ]
    # Optional: If you want to inject build-time ARGs
    # env:
    #   - 'NEXT_PUBLIC_IMGBB_API_KEY=secret-value'
    #   - 'NEXT_PUBLIC_STEADFAST_API_ID=secret-value'
    #   - 'NEXT_PUBLIC_STEADFAST_SECRET_KEY=secret-value'

  # 2. Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/robotic-gist-453607-t2/cloud-run-source-deploy/fc-frontend/fc-frontend",
      ]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "fc-frontend", # Name of your Cloud Run service
        "--image",
        "us-central1-docker.pkg.dev/robotic-gist-453607-t2/cloud-run-source-deploy/fc-frontend/fc-frontend",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "us-central1-docker.pkg.dev/robotic-gist-453607-t2/cloud-run-source-deploy/fc-frontend/fc-frontend"
