const colorOptions = [
  { value: 'Black', label: 'Black', color: '#000000' },
  { value: 'Brown', label: 'Brown', color: '#A52A2A' },
  { value: 'Beige', label: 'Beige', color: '#F5F5DC' },
  { value: 'Grey', label: 'Grey', color: '#808080' },
  { value: 'White', label: 'White', color: '#FFFFFF' },
  { value: 'Blue', label: 'Blue', color: '#0000FF' },
  { value: 'Petrol', label: 'Petrol', color: '#3B7A57' },
  { value: 'Turquoise', label: 'Turquoise', color: '#40E0D0' },
  { value: 'Green', label: 'Green', color: '#008000' },
  { value: 'Olive', label: 'Olive', color: '#808000' },
  { value: 'Yellow', label: 'Yellow', color: '#FFFF00' },
  { value: 'Orange', label: 'Orange', color: '#FFA500' },
  { value: 'Red', label: 'Red', color: '#FF0000' },
  { value: 'Pink', label: 'Pink', color: '#FFC0CB' },
  { value: 'Lilac', label: 'Lilac', color: '#C8A2C8' },
  { value: 'Gold', label: 'Gold', color: '#FFD700' },
  { value: 'Silver', label: 'Silver', color: '#C0C0C0' },
  { value: 'Aqua', label: 'Aqua', color: '#00FFFF' },
  { value: 'Aquamarine', label: 'Aquamarine', color: '#7FFFD4' },
  { value: 'Azure', label: 'Azure', color: '#F0FFFF' },
  { value: 'Bisque', label: 'Bisque', color: '#FFE4C4' },
  { value: 'BlanchedAlmond', label: 'Blanched Almond', color: '#FFEBCD' },
  { value: 'BlueViolet', label: 'Blue Violet', color: '#8A2BE2' },
  { value: 'BurlyWood', label: 'Burly Wood', color: '#DEB887' },
  { value: 'CadetBlue', label: 'Cadet Blue', color: '#5F9EA0' },
  { value: 'Chartreuse', label: 'Chartreuse', color: '#7FFF00' },
  { value: 'Chocolate', label: 'Chocolate', color: '#D2691E' },
  { value: 'Coral', label: 'Coral', color: '#FF7F50' },
  { value: 'CornflowerBlue', label: 'Cornflower Blue', color: '#6495ED' },
  { value: 'Cornsilk', label: 'Cornsilk', color: '#FFF8DC' },
  { value: 'Crimson', label: 'Crimson', color: '#DC143C' },
  { value: 'Cyan', label: 'Cyan', color: '#00FFFF' },
  { value: 'DarkBlue', label: 'Dark Blue', color: '#00008B' },
  { value: 'DarkCyan', label: 'Dark Cyan', color: '#008B8B' },
  { value: 'DarkGoldenRod', label: 'Dark GoldenRod', color: '#B8860B' },
  { value: 'DarkGray', label: 'Dark Gray', color: '#A9A9A9' },
  { value: 'DarkGreen', label: 'Dark Green', color: '#006400' },
  { value: 'DarkKhaki', label: 'Dark Khaki', color: '#BDB76B' },
  { value: 'DarkMagenta', label: 'Dark Magenta', color: '#8B008B' },
  { value: 'DarkOliveGreen', label: 'Dark Olive Green', color: '#556B2F' },
  { value: 'DarkOrange', label: 'Dark Orange', color: '#FF8C00' },
  { value: 'DarkOrchid', label: 'Dark Orchid', color: '#9932CC' },
  { value: 'DarkRed', label: 'Dark Red', color: '#8B0000' },
  { value: 'DarkSalmon', label: 'Dark Salmon', color: '#E9967A' },
  { value: 'DarkSeaGreen', label: 'Dark Sea Green', color: '#8FBC8F' },
  { value: 'DarkSlateBlue', label: 'Dark Slate Blue', color: '#483D8B' },
  { value: 'DarkSlateGray', label: 'Dark Slate Gray', color: '#2F4F4F' },
  { value: 'DarkTurquoise', label: 'Dark Turquoise', color: '#00CED1' },
  { value: 'DarkViolet', label: 'Dark Violet', color: '#9400D3' },
  { value: 'DeepPink', label: 'Deep Pink', color: '#FF1493' },
  { value: 'DeepSkyBlue', label: 'Deep Sky Blue', color: '#00BFFF' },
  { value: 'DimGray', label: 'Dim Gray', color: '#696969' },
  { value: 'DodgerBlue', label: 'Dodger Blue', color: '#1E90FF' },
  { value: 'FireBrick', label: 'Fire Brick', color: '#B22222' },
  { value: 'FloralWhite', label: 'Floral White', color: '#FFFAF0' },
  { value: 'ForestGreen', label: 'Forest Green', color: '#228B22' },
  { value: 'Fuchsia', label: 'Fuchsia', color: '#FF00FF' },
  { value: 'Gainsboro', label: 'Gainsboro', color: '#DCDCDC' },
  { value: 'GhostWhite', label: 'Ghost White', color: '#F8F8FF' },
  { value: 'Gold', label: 'Gold', color: '#FFD700' },
  { value: 'GoldenRod', label: 'Golden Rod', color: '#DAA520' },
  { value: 'GreenYellow', label: 'Green Yellow', color: '#ADFF2F' },
  { value: 'HoneyDew', label: 'Honey Dew', color: '#F0FFF0' },
  { value: 'HotPink', label: 'Hot Pink', color: '#FF69B4' },
  { value: 'IndianRed', label: 'Indian Red', color: '#CD5C5C' },
  { value: 'Indigo', label: 'Indigo', color: '#4B0082' },
  { value: 'Ivory', label: 'Ivory', color: '#FFFFF0' },
  { value: 'Khaki', label: 'Khaki', color: '#F0E68C' },
  { value: 'Lavender', label: 'Lavender', color: '#E6E6FA' },
  { value: 'LavenderBlush', label: 'Lavender Blush', color: '#FFF0F5' },
  { value: 'LawnGreen', label: 'Lawn Green', color: '#7CFC00' },
  { value: 'LemonChiffon', label: 'Lemon Chiffon', color: '#FFFACD' },
  { value: 'LightBlue', label: 'Light Blue', color: '#ADD8E6' },
  { value: 'LightCoral', label: 'Light Coral', color: '#F08080' },
  { value: 'LightCyan', label: 'Light Cyan', color: '#E0FFFF' },
  { value: 'LightGoldenRodYellow', label: 'Light Golden Rod Yellow', color: '#FAFAD2' },
  { value: 'LightGray', label: 'Light Gray', color: '#D3D3D3' },
  { value: 'LightGreen', label: 'Light Green', color: '#90EE90' },
  { value: 'LightPink', label: 'Light Pink', color: '#FFB6C1' },
  { value: 'LightSalmon', label: 'Light Salmon', color: '#FFA07A' },
  { value: 'LightSeaGreen', label: 'Light Sea Green', color: '#20B2AA' },
  { value: 'LightSkyBlue', label: 'Light Sky Blue', color: '#87CEFA' },
  { value: 'LightSlateGray', label: 'Light Slate Gray', color: '#778899' },
  { value: 'LightSteelBlue', label: 'Light Steel Blue', color: '#B0C4DE' },
  { value: 'LightYellow', label: 'Light Yellow', color: '#FFFFE0' },
  { value: 'Lime', label: 'Lime', color: '#00FF00' },
  { value: 'LimeGreen', label: 'Lime Green', color: '#32CD32' },
  { value: 'Linen', label: 'Linen', color: '#FAF0E6' },
  { value: 'Magenta', label: 'Magenta', color: '#FF00FF' },
  { value: 'Maroon', label: 'Maroon', color: '#800000' },
  { value: 'MediumAquaMarine', label: 'Medium Aqua Marine', color: '#66CDAA' },
  { value: 'MediumBlue', label: 'Medium Blue', color: '#0000CD' },
  { value: 'MediumOrchid', label: 'Medium Orchid', color: '#BA55D3' },
  { value: 'MediumPurple', label: 'Medium Purple', color: '#9370DB' },
  { value: 'MediumSeaGreen', label: 'Medium Sea Green', color: '#3CB371' },
  { value: 'MediumSlateBlue', label: 'Medium Slate Blue', color: '#7B68EE' },
  { value: 'MediumSpringGreen', label: 'Medium Spring Green', color: '#00FA9A' },
  { value: 'MediumTurquoise', label: 'Medium Turquoise', color: '#48D1CC' },
  { value: 'MediumVioletRed', label: 'Medium Violet Red', color: '#C71585' },
  { value: 'MidnightBlue', label: 'Midnight Blue', color: '#191970' },
  { value: 'MintCream', label: 'Mint Cream', color: '#F5FFFA' },
  { value: 'MistyRose', label: 'Misty Rose', color: '#FFE4E1' },
  { value: 'Moccasin', label: 'Moccasin', color: '#FFE4B5' },
  { value: 'NavajoWhite', label: 'Navajo White', color: '#FFDEAD' },
  { value: 'Navy', label: 'Navy', color: '#000080' },
  { value: 'OldLace', label: 'Old Lace', color: '#FDF5E6' },
  { value: 'OliveDrab', label: 'Olive Drab', color: '#6B8E23' },
  { value: 'OrangeRed', label: 'Orange Red', color: '#FF4500' },
  { value: 'Orchid', label: 'Orchid', color: '#DA70D6' },
  { value: 'PaleGoldenRod', label: 'Pale Golden Rod', color: '#EEE8AA' },
  { value: 'PaleGreen', label: 'Pale Green', color: '#98FB98' },
  { value: 'PaleTurquoise', label: 'Pale Turquoise', color: '#AFEEEE' },
  { value: 'PaleVioletRed', label: 'Pale Violet Red', color: '#DB7093' },
  { value: 'PapayaWhip', label: 'Papaya Whip', color: '#FFEFD5' },
  { value: 'PeachPuff', label: 'Peach Puff', color: '#FFDAB9' },
  { value: 'Peru', label: 'Peru', color: '#CD853F' },
  { value: 'Plum', label: 'Plum', color: '#DDA0DD' },
  { value: 'PowderBlue', label: 'Powder Blue', color: '#B0E0E6' },
  { value: 'Purple', label: 'Purple', color: '#800080' },
  { value: 'RebeccaPurple', label: 'Rebecca Purple', color: '#663399' },
  { value: 'RosyBrown', label: 'Rosy Brown', color: '#BC8F8F' },
  { value: 'RoyalBlue', label: 'Royal Blue', color: '#4169E1' },
  { value: 'SaddleBrown', label: 'Saddle Brown', color: '#8B4513' },
  { value: 'Salmon', label: 'Salmon', color: '#FA8072' },
  { value: 'SandyBrown', label: 'Sandy Brown', color: '#F4A460' },
  { value: 'SeaGreen', label: 'Sea Green', color: '#2E8B57' },
  { value: 'SeaShell', label: 'Sea Shell', color: '#FFF5EE' },
  { value: 'Sienna', label: 'Sienna', color: '#A0522D' },
  { value: 'SkyBlue', label: 'Sky Blue', color: '#87CEEB' },
  { value: 'SlateBlue', label: 'Slate Blue', color: '#6A5ACD' },
  { value: 'SlateGray', label: 'Slate Gray', color: '#708090' },
  { value: 'Snow', label: 'Snow', color: '#FFFAFA' },
  { value: 'SpringGreen', label: 'Spring Green', color: '#00FF7F' },
  { value: 'SteelBlue', label: 'Steel Blue', color: '#4682B4' },
  { value: 'Tan', label: 'Tan', color: '#D2B48C' },
  { value: 'Teal', label: 'Teal', color: '#008080' },
  { value: 'Thistle', label: 'Thistle', color: '#D8BFD8' },
  { value: 'Tomato', label: 'Tomato', color: '#FF6347' },
  { value: 'Violet', label: 'Violet', color: '#EE82EE' },
  { value: 'Wheat', label: 'Wheat', color: '#F5DEB3' },
  { value: 'YellowGreen', label: 'Yellow Green', color: '#9ACD32' },
  { value: 'Multi-coloured', label: 'Multi-coloured', color: 'linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet)' },
];


export default colorOptions;