export const tagOptions = [
  { value: "Casual", label: "Casual" },
  { value: "Formal", label: "Formal" },
  { value: "Sporty", label: "Sporty" },
  { value: "Trendy", label: "Trendy" },
  { value: "Business", label: "Business" },
  { value: "Streetwear", label: "Streetwear" },
  { value: "Athleisure", label: "Athleisure" },
  { value: "Smart Casual", label: "Smart Casual" },
  { value: "Vintage", label: "Vintage" },
  { value: "Summer", label: "Summer" },
  { value: "Winter", label: "Winter" },
  { value: "Comfort", label: "Comfort" },
  { value: "Luxury", label: "Luxury" },
  { value: "Eco-Friendly", label: "Eco-Friendly" },
  { value: "New Arrivals", label: "New Arrivals" },
  { value: "Best Sellers", label: "Best Sellers" },
  { value: "Sale", label: "Sale" },
  { value: "Limited Edition", label: "Limited Edition" },
  { value: "Customizable", label: "Customizable" },
  { value: "Athletic Fit", label: "Athletic Fit" },
  { value: "Slim Fit", label: "Slim Fit" },
  { value: "Regular Fit", label: "Regular Fit" },
  { value: "Tailored", label: "Tailored" },
  { value: "Breathable", label: "Breathable" },
  { value: "Water-Resistant", label: "Water-Resistant" },
  { value: "Lightweight", label: "Lightweight" },
  { value: "Warm", label: "Warm" },
  { value: "Stretch", label: "Stretch" }
];